CREATE TABLE PRODUCTO (
    ID_PRODUCTO VARCHAR (20) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (20) NOT NULL,
    PRECIO FLOAT NOT NULL,

);

CREATE TABLE CLIENTE (
    ID_CLIENTE VARCHAR (20) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (20) NOT NULL,
    CUIDAD VARCHAR (30) NOT NULL,

);

CREATE TABLE PEDIDO (
    ID_PEDIDO VARCHAR (20) NOT NULL PRIMARY KEY,
    FECHA DATE NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
    ON UPDATE CASCADE
    ON DELETE CASCADE

);

CREATE TABLE DETALLE_PEDIDO (
    ID_PEDIDO VARCHAR (20) NOT NULL,
    ID_PRODUCTO VARCHAR (20) NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
 /*
 INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,CUIDAD)
 VALUES ("290","JUAN","MANIZALES")   REPITA ESTE PROCESO 3 VECES


 SELECT * FROM CLIENTES;