CREATE TABLE CONDUCTOR {
    ID_CONDUCTOR INT NOT NULL,
    NOMBRE VARCHAR (45) NOT NULL,
    APELLIDO VARCHAR (45) NOT NULL,
    TELEFONO INT NOT NULL,
    DIRECCION VARCHAR (45) NOT NULL,
    PRIMARY KEY (ID_CONDUCTOR)
}

CREATE TABLE REVISION{
    ID_REVISION INT NOT NULL,
    FECHA_REVISION DATE NOT NULL,
    DIAGNOSTICO VARCHAR (45) NOT NULL,
    TIPO_REPARACION VARCHAR (45) NOT NULL,
    TIEMPO DATETIME NULL,
    PRIMARY KEY (ID_REVISION),
    FOREIGN KEY (VEHICULO_MATRICULA) REFERENCES VEHICULO(matricula) 
    FOREIGN KEY (VEHICULO_CONDUCTOR_ID_CONDUCTOR) REFERENCES VEHICULO(CONDUCTOR_ID_CONDUCTOR);
}

CREATE TABLE VEHICULO {
    matricula INT NOT NULL,
    modelo VARCHAR (45) NOT NULL,
    fabricante VARCHAR (45) NOT NULL,
    num_plazas INT NOT NULL
    caracteristicas VARCHAR (45) NOT NULL
    PRIMARY KEY (matricula),
    FOREIGN  (CONDUCTOR_ID_CONDUCTOR) REFERENCES CONDUCTOR(ID_CONDUCTOR);
}

CREATE TABLE VIAJE {
    ID_VIAJE INT NOT NULL,
    DESCRIPCION VARCHAR (45) NOT NULL,
    FECHA DATE NOT NULL,
    DISTANCIA INT NOT NULL,
    DESTINO VARCHAR (45) NOT NULL,
    PRIMARY KEY (ID_VIAJE)
}

CREATE TABLE RUTA {
    ID_RUTA INT NOT NULL,
    NOMBRE VARCHAR (45) NOT NULL,
    DESCRIPCION VARCHAR (45) NOT NULL,
    IMPORTE_FIJO VARCHAR (45) NOT NULL,
    TIEMPO_VIAJE VARCHAR (45) NOT NULL,
    FOREIGN KEY (SERVICIO_DIARIO_ID_SERVICIO) REFERENCES SERVICIO_DIARIO (ID_SERVICIO);
    FOREIGN KEY (VEHICULO_MATRICULA) REFERENCES VEHICULO(matricula);
}


CREATE TABLE SERVICIO_DIARIO{
    ID_SERVICIO INT NOT NULL,
    HORA_SALIDA VARCHAR (45) NOT NULL,
    HORA_LLEGADA VARCHAR (45) NOT NULL,
    DIAS_PROGRAMADOS VARCHAR (45) NOT NULL,
    DESCRIPCION VARCHAR (45)
    PRIMARY KEY (ID_SERVICIO)
    FOREIGN KEY (VIAJE_ID_VIAJE) REFERENCES VIAJE (ID_VIAJE);
}

CREATE TABLE PASAJERO {
    ID_PASAJERO INT NOT NULL,
    NOMBRE VARCHAR (45) NOT NULL,
    APELLIDO INT NOT NULL,
    TELEFONO INT NULL
    PRIMARY KEY (ID_PASAJERO)
    FOREIGN KEY (VIAJE_ID_VIAJE) REFERENCES VIAJE (ID_VIAJE);
}


CREATE TABLE VIAJE {
    ID_VIAJE INT NOT NULL,
    DESCRIPCION VARCHAR (45) NOT NULL,
    FECHA DATE NOT NULL,
    DISTANCIA INT NOT NULL,
    DESTINO VARCHAR (45) NULL,
    PRIMARY KEY (ID_VIAJE);
}

CREATE TABLE BILLETE {
    ID_BILLETE INT NOT NULL,
    NOMBRE VARCHAR (45) NOT NULL,
    FECHA_COMPRA DATE NOT NULL,
    IMPORTE VARCHAR (45) NOT NULL,
    HORA_SALIDA VARCHAR (45) NOT NULL,
    PRIMARY KEY (ID_BILLETE);

}

CREATE TABLE LISTADO {
    ID_LISTADO INT NOT NULL,
    ORDEN_CRONOLOGICO VARCHAR (45) NOT NULL,
    LUGARES_RELEVANTES VARCHAR (45) NOT NULL,
    PRIMARY KEY (ID_LISTADO);
}

CREATE TABLE LUGAR_RELEVANTE {
    NOMBRE VARCHAR (20) NOT NULL,
    HORA_PREVISTA VARCHAR (45) NOT NULL,
    ACTIVIDAD VARCHAR (45) NOT NULL,
    TIEMPO_PARADA VARCHAR (45) NOT NULL,
    PRIMARY KEY (NOMBRE);
}